/*USERS*/
DROP TABLE IF EXISTS LINKS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
  idU INT(12) AUTO_INCREMENT UNIQUE PRIMARY KEY,
  login VARCHAR(56) UNIQUE NOT NULL,
  password VARCHAR(56) NOT NULL
);

/*FOODS*/
DROP TABLE IF EXISTS LINKS;
DROP TABLE IF EXISTS WASEATEN;
DROP TABLE IF EXISTS FOODS;

CREATE TABLE FOODS (
  idF INT(12) AUTO_INCREMENT UNIQUE PRIMARY KEY,
  name VARCHAR(250) UNIQUE NOT NULL,
  calories REAL DEFAULT 0.0,
  proteins REAL DEFAULT 0.0,
  fats REAL DEFAULT 0.0,
  carbohydrates REAL DEFAULT 0.0
);

/*PROFILES*/
DROP TABLE IF EXISTS LINKS;
DROP TABLE IF EXISTS WASEATEN;
DROP TABLE IF EXISTS PROFILES;

CREATE TABLE PROFILES (
  idP INT(12) AUTO_INCREMENT UNIQUE PRIMARY KEY,
  name VARCHAR(56),
  surname VARCHAR(56),
  sex VARCHAR(10),
  birthday DATE,
  height REAL DEFAULT 0.0,
  weight REAL DEFAULT 0.0,
  activeTime INT(3) DEFAULT 0
);

/*WASEATEN*/
DROP TABLE IF EXISTS WASEATEN;

CREATE TABLE WASEATEN (
  idWE INT(12) AUTO_INCREMENT UNIQUE PRIMARY KEY,
  idP INT(12),
  idF INT(12),
  dateWE DATE NOT NULL,
  CONSTRAINT FK_WEP FOREIGN KEY (idP) REFERENCES PROFILES (idP),
  CONSTRAINT FK_WEF FOREIGN KEY (idF) REFERENCES FOODS (idF)
);

/*NORMS*/
DROP TABLE IF EXISTS LINKS;
DROP TABLE IF EXISTS NORMS;

CREATE TABLE NORMS (
  idN INT(12) AUTO_INCREMENT UNIQUE PRIMARY KEY,
  calories INT(12) DEFAULT 0,
  proteins INT(12) DEFAULT 0
);

/*LINKS*/
DROP TABLE IF EXISTS LINKS;

CREATE TABLE LINKS (
  idL INT(12) AUTO_INCREMENT UNIQUE PRIMARY KEY,
  idU INT(12),
  idP INT(12),
  idN INT(12),
  CONSTRAINT FK_LU FOREIGN KEY (idU) REFERENCES USERS (idU),
  CONSTRAINT FK_LP FOREIGN KEY (idP) REFERENCES PROFILES (idP),
  CONSTRAINT FK_LN FOREIGN KEY (idN) REFERENCES NORMS (idN)
);